#org.gradle.cache.cleanup=false
org.gradle.jvmargs=-Xmx4G

mod_archives_base_name=litematica-printer
mod_description=Printer All Version
mod_homepage=https://space.bilibili.com/31545812
mod_id=litematica-printer
mod_license=CC0-1.0
mod_maven_group=com.zhaixianyu
mod_name=Litematica-Printer
mod_sources=https://github.com/zhaixianyu/litematica-printer
mod_version=2.4

loader_version=0.18.4
pinyin_version = 2.5.1
