minecraft_dependency= 1.21.11
#https://fabricmc.net/develop/
minecraft_version=1.21.11
yarn_mappings=1.21.11+build.4

# Fabric API
fabric_api_version=0.141.3+1.21.11

#https://www.curseforge.com/minecraft/mc-mods/malilib/files/all
#https://modrinth.com/mod/malilib
malilib=0.27.7
#https://www.curseforge.com/minecraft/mc-mods/item-scroller/files/all
#https://modrinth.com/mod/itemscroller
item_scrolle=0.30.2
#https://www.curseforge.com/minecraft/mc-mods/litematica/files/all
#https://modrinth.com/mod/litematica
#https://modrinth.com/mod/litematica/versions
litematica=0.26.2
#https://www.curseforge.com/minecraft/mc-mods/tweakeroo/files/all?
#https://modrinth.com/mod/tweakeroo
tweakeroo=0.27.5
#https://jitpack.io/#MoRanpcy/quickshulker
quick_shulker=2.10.0-1.21.11

#https://modrinth.com/mod/carpet/versions
#https://www.curseforge.com/minecraft/mc-mods/carpet/files/all
carpet=7367605

#https://modrinth.com/mod/chest-tracker-port/versions
chesttracker=2.8.1+1.21.11
#https://modrinth.com/mod/where-is-it-port/versions?l=fabric
whereisit=2.7.3+1.21.11
#https://github.com/ponuing/JackFredLib/releases
jackfredlib=0.10.6+1.21.11
#https://maven.blamejared.com/com/blamejared/searchables/
#https://modrinth.com/mod/searchables/versions?l=fabric
searchables=Searchables-fabric-1.21.11:1.0.2
#https://modrinth.com/mod/yacl/versions?l=fabric
yacl=3.8.2+1.21.11-fabric
#https://modrinth.com/mod/modmenu/versions
modmenu=17.0.0
#where_is_it=2.3.1+1.20.2
#searchables=Searchables-fabric-1.20.2:1.0.16

#rein=13.0.666
#architecturyn=10.0.8
#cloth_config=12.0.109
#libguin=8.1.0+1.20.1
#LibGui=6